name       : libsoup3
version    : 3.2.1
release    : 3
source     :
    - https://download.gnome.org/sources/libsoup/3.2/libsoup-3.2.1.tar.xz : b1eb3d2c3be49fbbd051a71f6532c9626bcecea69783190690cd7e4dfdf28f29
license    : LGPL-2.1-only
component  : desktop.gnome.core
emul32     : yes
summary    : GNOME HTTP client/server library
description: |
    The libsoup is HTTP client/server library for GNOME. It uses GObject and the GLib main loop to integrate with GNOME applications and it also has asynchronous API for use in threaded applications.
builddeps  :
    - pkgconfig32(gio-2.0)
    - pkgconfig32(gnutls)
    - pkgconfig32(krb5)
    - pkgconfig32(libbrotlicommon)
    - pkgconfig32(libnghttp2)
    - pkgconfig32(libpsl)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(sqlite3)
    - glib-networking
    - glib-networking-32bit
    - vala
rundeps    :
    - glib-networking
    - 32bit :
        - glib-networking-32bit
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi
    %meson_configure -Dautobahn=disabled -Dinstalled_tests=false -Dintrospection=$build_gobject -Dsysprof=disabled -Dtests=false -Dtls_check=false
build      : |
    %ninja_build
install    : |
    %ninja_install
    sed -i 's/sysprof-capture-4, //' $installdir/%libdir%/pkgconfig/*.pc
